python_test_utils(
    name="test_utils",
)

python_sources()

python_tests(
    name="tests0",
    dependencies=["src/psycop/training/tests/test_data:synth_data"],
)

files(
    name="test_config",
    sources=["config/**"],
)
